# Generated by Django 3.2 on 2021-05-02 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local', models.CharField(blank=True, max_length=12, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('valor_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_tabela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('datahora', models.DateTimeField(auto_now_add=True)),
                ('tempo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
